# Tasca S10.01. Analítica de dades en Pandas

### Instalación e importación de librerias que he utilizado para resolver los ejercicios:

In [1]:
# !pip install pandas
import pandas as pd
import numpy as np
from datetime import datetime

# !pip install matplotlib
import matplotlib.pyplot as plt

# !pip install seaborn
import seaborn as sns

# NIVELL 1

## 1.
* Importa com un DataFrame l'arxiu sprint10.xlsx. Assegura't que el fitxer s'importa correctament, amb els noms de columnes que li corresponen, sense manipular l'arxiu original.
* Ordena el DataFrame pel país d'origen. En cas d'empat, ordena pel nom de la ciutat.
* Mostra les primeres 10 files.
- Addicionalment, fes un print on comprovi que el DNI només té valors únics.

In [3]:
dfEncuesta = pd.read_excel("sprint10.xlsx", index_col= 0, skiprows=3)

In [4]:
dfEncuesta

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1.216 €,NaN,1.0,Grup B
996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971 €,NaN,1.0,Grup A
997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682 €,NaN,1.0,Grup A
998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1.699 €,1.0,NaN,Grup C
999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1.217 €,NaN,1.0,Grup A

In [5]:
# Ordeno por país y luego por ciudad
dfEncuesta = dfEncuesta.sort_values(by=["País d'origen", "Ciutat"])

In [6]:
dfEncuesta

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B
728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A
751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A
854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A
872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A

In [7]:
# Muestro las primeras 10 filas
dfEncuesta.head(10)

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,1.0,NaN,Grup A
281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,1.0,Grup A
435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,1.0,Grup C
444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,1.0,NaN,Grup C
487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,1.0,Grup B

In [8]:
# Compruebo si el DNI es único
esUnico = dfEncuesta["DNI"].is_unique
print(f"¿El DNI tiene valores únicos?: {esUnico}")

¿El DNI tiene valores únicos?: True

## 2.
* Crea una columna que sigui el nom complet.
* Crea una columna si la persona és nascuda a Espanya o no.
* Posa el DNI com a índex del DataFrame (noms de files).
* Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.
* Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).
- Mostra tots els canvis que has realitzat en una sola taula.

### Soluciones

* Crea una columna que sigui el nom complet.

In [9]:
# Creo la columna de nombre completo combinando Nom y Cognoms
dfEncuesta["Nom Complet"] = dfEncuesta["Nom"] + " " + dfEncuesta["Cognoms"]

* Crea una columna si la persona és nascuda a Espanya o no.

In [10]:
# Creo columna para saber si nació en España basado en 'País d'origen'
dfEncuesta["Nascut a Espanya"] = dfEncuesta["País d'origen"].apply(lambda x: "Sí" if x == "Espanya" else "No")

* Posa el DNI com a índex del DataFrame (noms de files).

In [11]:
# Pongo el DNI como índex del DataFrame
dfEncuesta.set_index("DNI", inplace=True)

* Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.

In [12]:
# Renombro las columnas de nacimiento por nombres más cortos
dfEncuesta.rename(columns={
    "Dia de Naixement" : "Dia",
    "Mes de Naixement" : "Mes",
    "Any de Naixement" : "Any"
}, inplace=True)

* Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).

In [13]:
# Traduzco las siglas del género y convierto NC en un valor nulo (NaN) con la libreria Numpy para que Pandas los ignore en promedios y sumas.

traduccionesGeneroYnc = {"H": "Home", "D": "Dona", "A": "Altres", "NC": np.nan}
dfEncuesta["Gènere"] = dfEncuesta["Gènere"].replace(traduccionesGeneroYnc)

- Mostra tots els canvis que has realitzat en una sola taula.

In [14]:
dfEncuesta

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom Complet,Nascut a Espanya
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,No
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,1.0,NaN,Grup B,Mia Fischer,No
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,1.0,NaN,Grup D,Jonas Schneider,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones,No
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,1.0,NaN,Grup A,George Brown Jones,No
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown,No
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,NaN,1.0,Grup A,Isla Jones Brown,No
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,1.0,NaN,Grup A,William Smith,No

## 3.
* Junta les columnes Fills i No Fills en una sola columna, utilitzant el mètode .apply() i definint una funció que resolgui el problema. 
* La columna nova ha de dir-se "Fills" i prendre els valors "Sí" o "No".

### Soluciones

* Junta les columnes Fills i No Fills en una sola columna, utilitzant el mètode .apply() i definint una funció que resolgui el problema.

In [15]:
# Unifico las columnas "Fills" y "No Fills" en una sola
def procesarHijos(fila):
    # Si la columna Fills tiene un valor (True), devuelve "Sí"
    if not np.isnan(fila["Fills"]) if isinstance(fila["Fills"], float) else fila["Fills"]:
        return "Sí"
    # Si la columna No Fills tiene un valor, devuelve "No"
    return "No"

In [16]:
dfEncuesta['FillsFinal'] = dfEncuesta.apply(procesarHijos, axis=1)

* La columna nova ha de dir-se "Fills" i prendre els valors "Sí" o "No".

In [17]:
# Elimino las columnas viejas y renombramos la nueva
dfEncuesta.drop(columns=["Fills", "No Fills"], inplace=True)
dfEncuesta.rename(columns={"FillsFinal": "Fills"}, inplace=True)

In [18]:

# Muestro el resultado final de la tabla
dfEncuesta.head()

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Grup Professional,Nom Complet,Nascut a Espanya,Fills
DNI,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,Grup A,Mia Schneider Fischer,No,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Grup B,Laura Schneider Fischer,No,Sí
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,Grup B,Lea Schneider Schneider,No,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Grup B,Mia Fischer,No,Sí
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Grup D,Jonas Schneider,No,Sí

## 4.
* Crea una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere.
- Ordena la taula en funció del sou mig.

### Soluciones

In [19]:
# Limpio la columna de salario: quito "€" y el punto de los miles, luego lo convierto a número
dfEncuesta["Salari mensual"] = dfEncuesta["Salari mensual"].str.replace(" €", "", regex=False).str.replace(".", "", regex=False).astype(float)

# 2. Creo la tabla resumen agrupando por "Gènere"
# Uso .agg() para pedir la media (mean), mediana (median), mínimo y máximo a la vez. 
# Lo hago como string porque usando np.mean, np.median, np.min, np.max me devuelve un aviso indicando que en versiones futuras de Pandas se usará directamente en un "string".
tablaResumen = dfEncuesta.groupby("Gènere")["Salari mensual"].agg(["mean", "median", "min", "max"]).round(2)

In [20]:
# 3. Ordeno la tabla según el sueldo medio ("mean") de menor a mayor
tablaResumen = tablaResumen.sort_values(by="mean")

# Muestro la tabla resumen
tablaResumen

           mean  median    min     max
Gènere
Dona    1469.44  1361.5  665.0  3021.0
Altres  1626.59  1545.0  703.0  3175.0
Home    1643.25  1531.0  737.0  3356.0

## 5.
* Crea una taula resum amb el salari mig per gènere (files) i país d'origen (columnes).

- Afegeix-hi les mitjanes als marges de la taula.

- (EXTRA): Aplica format condicional a la taula per veure en un color més intens els valors

In [21]:
# 1. Creo la tabla dinámica cruzando Género y País
# Añado automáticamente las medias totales en los bordes con margins=True
tablaDinamica = dfEncuesta.pivot_table(
    values="Salari mensual", 
    index="Gènere", 
    columns="País d'origen", 
    aggfunc="mean", 
    margins=True)

In [22]:
# 2. Aplico el formato condicional (Extra)
# Uso un mapa de colores para resaltar visualmente los salarios más altos
objetoTablaDinamica = tablaDinamica.style.background_gradient(cmap="Blues")

In [23]:
# Muestro el resultado
objetoTablaDinamica

## 6.
* Crea una columna nova que sigui la data de naixament en format Datetime a partir de les columnes dia, mes i any. 
* Utilitzant aquesta columna crea una funció que donada una data, et calculi l'edat actual a dia d'avui.
- Utilitza la funció que acabes de crear per generar una columna nova al DataFrame amb l'edat actual.

In [24]:
# Creo la columna "Data de Naixement" combinando las columnas de la tabla
# Renombro temporalmente las columnas para que Pandas las reconozca automáticamente
dfEncuesta["Data de Naixement"] = pd.to_datetime(dfEncuesta[["Dia", "Mes", "Any"]].rename(columns={
    "Dia": "day",
    "Mes": "month",
    "Any": "year"}))

In [25]:
# Defino la función para calcular la edad exacta
def calcularEdad(dataNaixement):
    dataActual = datetime.now()
    # Resto los años
    edat = dataActual.year - dataNaixement.year
    # Compruebo si ya ha pasado el cumpleaños este año
    # Si el mes/día actual es menor al de nacimiento, resta 1
    haPassatAniversari = (dataActual.month, dataActual.day) >= (dataNaixement.month, dataNaixement.day)
    if not haPassatAniversari:
        edat -= 1
    return edat

In [26]:
# Aplico la función para generar la nueva columna "Edat"
dfEncuesta["Edat"] = dfEncuesta["Data de Naixement"].apply(calcularEdad)

In [27]:
# Muestro las columnas relevantes para verificar
dfEncuesta[["Data de Naixement", "Edat"]].head()

          Data de Naixement  Edat
DNI
28973553Z        1976-10-22    49
37399141L        1958-02-02    68
37368317L        2005-10-23    20
21390098Z        1950-08-11    75
44060014R        1985-11-22    40

# NIVELL 2

## 1.
* Utilitzant el següent DataFrame, adjunta la columna "Increment" al dataframe del nivell anterior.
* Actualitza la columna salari en funció dels percentatges que s'adjunten. No modifiquis manualment els increments, escriu codi Python per fer les conversions necessàries.

df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":

["5%","3,5%","2%","8%"]})

In [28]:
# Creo el DataFrame de incrementos del enunciado
dfIncrement = pd.DataFrame({
    "Grup Professional": ["Grup A", "Grup B", "Grup C", "Grup D"],
    "Increment": ["5%", "3,5%", "2%", "8%"]})

# Limpio la columna "Increment"
# Quito el "%", cambio la coma por punto y divido por 100
dfIncrement["Increment"] = dfIncrement["Increment"].str.replace("%", "", regex=False).str.replace(",", ".", regex=False).astype(float) / 100

In [29]:
dfIncrement

  Grup Professional  Increment
0            Grup A      0.050
1            Grup B      0.035
2            Grup C      0.020
3            Grup D      0.080

In [30]:
dfEncuesta

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Grup Professional,Nom Complet,Nascut a Espanya,Fills,Data de Naixement,Edat
DNI,,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951.0,Grup A,Mia Schneider Fischer,No,No,1976-10-22,49
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1769.0,Grup B,Laura Schneider Fischer,No,Sí,1958-02-02,68
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2013.0,Grup B,Lea Schneider Schneider,No,No,2005-10-23,20
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1557.0,Grup B,Mia Fischer,No,Sí,1950-08-11,75
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2754.0,Grup D,Jonas Schneider,No,Sí,1985-11-22,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2033.0,Grup B,Emily Taylor Jones,No,No,1958-03-28,67
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1130.0,Grup A,George Brown Jones,No,Sí,1979-12-27,46
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1023.0,Grup A,Olivia Brown Brown,No,No,1952-08-28,73
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1197.0,Grup A,Isla Jones Brown,No,No,1999-03-28,26
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1405.0,Grup A,William Smith,No,Sí,1997-05-19,28

In [31]:
# Uno (merge) la información de incrementos a mi dfEncuesta original
# Reseteo el índice temporalmente para no perder el DNI durante la unión
dfEncuesta = pd.merge(dfEncuesta.reset_index(), dfIncrement[["Grup Professional", "Increment"]], on="Grup Professional", how="left")

# Actualizo la columna de salario aplicando la fórmula: Salario * (1 + Incremento)
dfEncuesta["Salari mensual"] = dfEncuesta["Salari mensual"] * (1 + dfEncuesta["Increment"])

# Restauro el DNI como índice y elimino la columna auxiliar de incremento si ya no la necesito
dfEncuesta.set_index("DNI", inplace=True)

# Muestro las primeras filas para verificar el aumento 
dfEncuesta[["Grup Professional", "Salari mensual"]].head()

          Grup Professional  Salari mensual
DNI
28973553Z            Grup A         998.550
37399141L            Grup B        1830.915
37368317L            Grup B        2083.455
21390098Z            Grup B        1611.495
44060014R            Grup D        2974.320

## 2.
* Utilitzant un bucle, exporta en 4 fitxers (format .xlsx o .csv) les dades de cada Grup Professional.

* Per exemple: "dades_GrupA.xlsx" , "dades_GrupB.xlsx" ...
- Exporta un 5è DataFrame en format .xlsx o .csv que contingui quants treballadors hi ha per cada Grup Professional, quin és el seu sou mig i quina és la seva edat mediana.

In [32]:
# Exporto los 4 ficheros individuales usando un bucle
# Obtengo los nombres únicos de los grupos que hay en la columna
listaGrupos = dfEncuesta["Grup Professional"].unique()

for grupo in listaGrupos:
    # Filtro el DataFrame para el grupo actual
    dfFiltrado = dfEncuesta[dfEncuesta["Grup Professional"] == grupo]
    
    # Limpio el nombre para el archivo (quito espacios si los hay)
    nombreLimpio = grupo.replace(" ", "")
    nombreArchivo = f"dades{nombreLimpio}.xlsx"
    
    # Exporto a Excel
    dfFiltrado.to_excel(nombreArchivo)
    print(f"Archivo generado: {nombreArchivo}")


# Creo el quinto DataFrame con el resumen estadístico
# Agrupo por grupo y pido: tamaño (count), media de sueldo y mediana de edad
dfResumenFinal = dfEncuesta.groupby("Grup Professional").agg({
    "Nom": "count",
    "Salari mensual": "mean",
    "Edat": "median"})

# Renombro las columnas para que el Excel quede profesional
dfResumenFinal.columns = ["Total Treballadors", "Sou Mig", "Edat Mediana"]

# 3. Exportamos el resumen a Excel
dfResumenFinal.to_excel("resumGrupsProfessionals.xlsx")

print("\n¡El informe resumen ha sido exportado correctamente!")

Archivo generado: dadesGrupA.xlsx
Archivo generado: dadesGrupB.xlsx
Archivo generado: dadesGrupD.xlsx
Archivo generado: dadesGrupC.xlsx

¡El informe resumen ha sido exportado correctamente!

# NIVELL 3

### El nivell 3 d’aquest sprint és totalment diferent a d’altres sprints que has fet fins ara, ja que són exercicis més abstractes que requereixen barallar-s’hi bastant. 
### No continuen amb el mateix dataset dels nivells anteriors, sinó que et plantegen dues situacions noves totalment diferents entre elles.

## 1.
### Crea una funció que prengui un dataframe com a paràmetre d'entrada.
### La funció ha de crear (i exportar) un gràfic automàticament per a cada columna del dataframe. Per exemple:

* un histograma/boxplot si la variable és numèrica
* unes barres dels valors més freqüents si és categòrica
* unes barres dels anys més freqüents si la dada està en format data.

### La idea és crear una funció que funcioni per qualsevol dataframe, no només amb el que hem treballat fins ara.

### Mostra el resultat de la funció en algun dels datasets d’exemple que conté el paquet seaborn. Per exemple, iris, penguins o titanic.

- Tingues en consideració que en el següent sprint treballaràs exclusivament amb gràfics. 
- L’objectiu d’aquest exercici no és crear gràfics molt elaborats, sinó resoldre una necessitat de manera ràpida i automàtica.

### Código de la función

In [33]:
def generarGraficosAutomaticos(dfEntrada):
    # Recorre cada columna y genera un gráfico según su contenido.
    for columna in dfEntrada.columns:
        # Detecta el tipo de dato de la columna
        esNumerico = pd.api.types.is_numeric_dtype(dfEntrada[columna])
        esFecha = pd.api.types.is_datetime64_any_dtype(dfEntrada[columna])
        
        plt.figure(figsize=(8, 4))
        
        if esFecha:
            # Gráfico de barras de años más frecuentes
            años = dfEntrada[columna].dt.year.value_counts().sort_index()
            años.plot(kind="bar", color="skyblue")
            plt.title(f"Frecuencia por Año: {columna}")
        
        elif esNumerico:
            # Histograma para variables numéricas
            sns.histplot(dfEntrada[columna].dropna(), kde=True, color="salmon")
            plt.title(f"Distribución Numérica: {columna}")
        
        else:
            # Barras de valores más frecuentes para categorías
            topValors = dfEntrada[columna].value_counts().head(10)
            topValors.plot(kind="bar", color="lightgreen")
            plt.title(f"Top 10 Valores: {columna}")
            plt.xticks(rotation=45)

        plt.tight_layout()
        nombreArchivo = f"grafico{columna}.png"
        plt.savefig(nombreArchivo)
        plt.close()
        print(f"Archivo exportado: {nombreArchivo}")

In [34]:
# Lista completa de todos los datasets disponibles para practicar
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [35]:
# Cargo el dataset "iris"
dfIris = sns.load_dataset("iris")

# (Opcional) Veo qué pinta tiene
print("Dataset cargado correctamente.")
print("5 Primeras filas:")
print(dfIris.head())

# Llamo a la función que he desarrollado antes
# Esta función genera y guarda un gráfico por cada columna de "iris"
generarGraficosAutomaticos(dfIris)

Dataset cargado correctamente.
5 Primeras filas:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
Archivo exportado: graficosepal_length.png
Archivo exportado: graficosepal_width.png
Archivo exportado: graficopetal_length.png
Archivo exportado: graficopetal_width.png
Archivo exportado: graficospecies.png

## 2.
* Carrega l'arxiu matriu_distancies.xlsx a pandas, de manera que els noms de files i els noms de columnes siguin els de les ciutats. 
* Borra "Las Palmas de Gran Canaria" i "Palma" perquè poguem fer el trajecte en cotxe.

##### Ens interessa visitar totes les ciutats principals d'Espanya recorrent la mínima distància possible.

##### No cal que ho facis de forma òptima, ens interessa que desenvolupis una solució raonable utilitzant les eines que tens actualment.

##### Per exemple, una aproximació senzilla (que no òptima) seria anant sempre a la ciutat més propera que no haguem visitat encara

##### Fes una funció que donada la matriu de distàncies i la ciutat d'origen, faci una proposta de ruta que sigui el més curta possible que puguis, retornant una llista amb l'ordre de visita. Dóna també la distància total recorreguda.

##### (EXTRA) Des de quina ciutat la ruta seria més curta amb l'algoritme plantejat

### Código de la función

In [36]:
# Cargo y limpio la matriz
dfDistancias = pd.read_excel("matriu_distancies.xlsx", index_col=0)
ciudadesABorrar = ["Las Palmas de Gran Canaria", "Palma"]
dfDistanciasLimpio = dfDistancias.drop(columns=ciudadesABorrar, errors="ignore").drop(index=ciudadesABorrar, errors="ignore")
dfDistanciasLimpio = dfDistanciasLimpio.fillna(0) # La distancia a uno mismo es 0

def calcularRutaMasCorta(matrizDistancias, ciudadOrigen, mostrarResultados=True):

    # Propuesta de ruta basada en el vecino más cercano.
    # Inicializo las listas necesarias para devolver un DataFrame con el desglose paso a paso
    ciudadesPendientes = list(matrizDistancias.index)
    ciudadesPendientes.remove(ciudadOrigen)
    
    listaOrden = [1]
    listaCiudades = [ciudadOrigen]
    listaDistanciaTramo = [0.0]
    listaDistanciaAcumulada = [0.0]
    
    distanciaTotal = 0.0
    ciudadActual = ciudadOrigen
    paso = 2
    
    while ciudadesPendientes:
        # Buscamos la distancia a las ciudades que quedan
        distanciasActuales = matrizDistancias.loc[ciudadActual, ciudadesPendientes]
        proximaCiudad = distanciasActuales.idxmin()
        distanciaTram = distanciasActuales.min()
        
        # Actualizamos la ruta
        distanciaTotal += distanciaTram
        
        # Registro los datos de cada tramo en mis listas para construir el informe
        listaOrden.append(paso)
        listaCiudades.append(proximaCiudad)
        listaDistanciaTramo.append(distanciaTram)
        listaDistanciaAcumulada.append(distanciaTotal)
        
        ciudadesPendientes.remove(proximaCiudad)
        ciudadActual = proximaCiudad
        paso += 1
        
    # Construyo el DataFrame final con toda la información recolectada
    dfResultadoRuta = pd.DataFrame({
        "Orden": listaOrden,
        "Ciudad": listaCiudades,
        "Distancia Tramo (km)": listaDistanciaTramo,
        "Distancia Acumulada (km)": listaDistanciaAcumulada})
    
    # Realizo las impresiones dentro de la función para que el usuario no tenga que gestionar los prints
    if mostrarResultados:
        # Primero convierto el DataFrame a string para medir su ancho real
        tablaTexto = dfResultadoRuta.to_string(index=False)
        anchoTabla = max(len(linea) for linea in tablaTexto.split('\n'))
        
        # Uso el ancho calculado para centrar cada línea de texto
        print(f"Resultados de la ruta empezando en: {ciudadOrigen}".center(anchoTabla))
        print(f"Distancia total recorrida: {distanciaTotal} km".center(anchoTabla))
        print("\n" + "<< Desglose de la ruta optimizada >>".center(anchoTabla))
        print(tablaTexto)
        print("-" * anchoTabla) # Ajusto también la línea de separación al ancho de la tabla
        print("\n")
    
    return dfResultadoRuta

# ¿Desde qué ciudad la ruta es más corta?
# Calculo el kilometraje total para cada ciudad de la matriz para encontrar el origen óptimo sin generar ruido por pantalla
resultadosKilometraje = {}
for ciudad in dfDistanciasLimpio.index:
    # Obtengo el DataFrame para comparar las distancias acumuladas finales
    dfTemporal = calcularRutaMasCorta(dfDistanciasLimpio, ciudad, mostrarResultados=False)
    resultadosKilometraje[ciudad] = dfTemporal["Distancia Acumulada (km)"].iloc[-1]

# Determino cuál es la mejor ciudad comparando los resultados de mi diccionario
mejorCiudadOrigen = min(resultadosKilometraje, key=resultadosKilometraje.get)

### Llamada de la función

In [37]:
# Ejecuto la llamada definitiva para la mejor ciudad encontrada; la propia función se encargará de imprimir todo
dfMejorRuta = calcularRutaMasCorta(dfDistanciasLimpio, mejorCiudadOrigen)

                Resultados de la ruta empezando en: Barcelona
                     Distancia total recorrida: 2778.0 km

                     << Desglose de la ruta optimizada >>
 Orden                  Ciudad  Distancia Tramo (km)  Distancia Acumulada (km)
     1               Barcelona                   0.0                       0.0
     2 Hospitalet de Llobregat                   7.0                       7.0
     3                Zaragoza                 250.0                     257.0
     4                Valencia                 246.0                     503.0
     5                Alicante                 125.0                     628.0
     6                  Murcia                  69.0                     697.0
     7                 Córdoba                 320.0                    1017.0
     8                 Sevilla                 121.0                    1138.0
     9                  Málaga                 158.0                    1296.0
    10              Valladolid                 549.0                    1845.0
    11                   Gijón                 224.0                    2069.0
    12                  Bilbao                 223.0                    2292.0
    13                    Vigo                 486.0                    2778.0
------------------------------------------------------------------------------